### ISSUE TITLE
Implement Refresh token

### ISSUE THREAD

**Issue by jcomoto** [ksquareincmx/conference-server-next#38]
Due to the short lifespan of a JWT we need to implement a refresh token to allow users to keep using the app without the need of authenticating again.

- [ ] #36 Send refresh token on authentication request
- [ ] #37 Add `/refreshToken` endpoint 
- [ ] Reduce JWT lifespan to 12 hrs
- [ ] Make a scheduled task to remove expired tokens
